name: CI - RSpec
on:
  push:
    branches:
      - main
  pull_request: # all branches
jobs:
  ruby_3_0_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Set to Ruby 3.0.0
      run: |
        echo "3.0.0" > .ruby-version
        VERSION=`cat .ruby-version` && echo "Using Ruby ${VERSION}"

    - uses: ruby/setup-ruby@v1

    - name: Bundle install
      run: |
        gem install bundler --no-document
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: bundle exec rspec
  ruby_2_7_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: ruby/setup-ruby@v1

      - name: Bundle install
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run RSpec
        run: bundle exec rspec
  ruby_2_6_5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Set to Ruby 2.6.5
      run: |
        echo "2.6.5" > .ruby-version
        VERSION=`cat .ruby-version` && echo "Using Ruby ${VERSION}"

    - uses: ruby/setup-ruby@v1

    - name: Bundle install
      run: |
        gem install bundler --no-document
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: bundle exec rspec